export const data = [
  {id: '1', icon: 'ios-home', lable: 'Dashboard'},
  {id: '1', icon: 'ios-aperture', lable: 'Employees Sign In'},
  {id: '1', icon: 'ios-bicycle', lable: 'Nails Tech Sign In'},
  {id: '1', icon: 'ios-bed', lable: 'Customer Sign In'},
  {id: '1', icon: 'ios-boat', lable: 'Dashboard'},
  {id: '1', icon: 'ios-bug', lable: 'Dashboard'},
  {id: '1', icon: 'ios-bookmarks', lable: 'Dashboard'},
  {id: '1', icon: 'ios-build', lable: 'Dashboard'},
  {id: '1', icon: 'ios-bookmark', lable: 'Dashboard'},
];
export const items = [
  { code: "#4E4845" },
  { code: "#B52988" },
  { code: "#4F276F" },
  { code: "#00DAFE" },
  { code: "#070E3A" },
  { code: "#C49F1C" },
  { code: "#DEDDDE" },
  { code: "#B03340" },
  { code: "#379EB2" },
  { code: "#E5DFCD" },
  { code: "#C34867" },
  { code: "#E38081" },
  { code: "#4E4845" },
  { code: "#DF4626" },
  { code: "#4E4845" },
  { code: "#3C7ECD" },
  { code: "#4E4845" },
];
export const items1 = [
  { code: "#4E4845" },
  { code: "#B52988" },
  { code: "#4F276F" },
  { code: "#00DAFE" },
  { code: "#070E3A" },
  { code: "#C49F1C" },
  { code: "#DEDDDE" },
];