export const data = [
  {id: '25', icon: 'ios-cafe', lable: 'BACKOFFICE'},
  {id: '15', icon: 'ios-card', lable: 'PAYMENT'},
  {id: '1111', icon: 'ios-gift', lable: 'GIFTCARD'},
  {id: '12', icon: 'ios-aperture', lable: 'EMPLOYEES'},
  {id: '13', icon: 'ios-bicycle', lable: 'NAILS TECH'},
  {id: '14', icon: 'ios-bed', lable: 'CUSTOMER'},
  {id: '17', icon: 'ios-tv', lable: 'APPOINTMENT'},
  {id: '11', icon: 'ios-bookmark', lable: 'TIPS ADJS'},
  {id: '19', icon: 'ios-book', lable: 'CLOSEOUT'},
  {id: '18', icon: 'ios-build', lable: 'NAILS SUPPLY'},
  {id: '18', icon: 'ios-build', lable: 'TURN SYSTEM'},
  // { id: '1', icon: 'ios-home', lable: 'Dashboard' },

  // {id: '16', icon: 'ios-bug', lable: 'Manager System'},

  // { id: '10', icon: 'ios-card', lable: 'Connect Credit Card' },
];
export const items = [
  {code: '#4E48454E4845'},
  {code: '#B52988'},
  {code: '#4F276F'},
  {code: '#00DAFE'},
  {code: '#070E3A'},
  {code: '#C49F1C'},
  {code: '#DEDDDE'},
  {code: '#B03340'},
  {code: '#379EB2'},
  {code: '#E5DFCD'},
  {code: '#C34867'},
  {code: '#E38081'},
  {code: '#4E4845'},
  {code: '#DF4626'},
  {code: '#4E4845'},
  {code: '#3C7ECD'},
  {code: '#4E4845'},
];
export const QUICK_MENU = [
  {code: '#2DFFFE', service: 'MAINCURE'},
  {code: '#0303FF', service: 'PEDICURE'},
  {code: '#FF67B3', service: 'FULL SET'},
  {code: '#6394EB', service: 'REFILL'},
  {code: '#008000', service: 'WAX'},
  {code: '#2DFFFE', service: 'FACIAL'},
  {code: '#6394EB', service: 'EYELASHES'},
  // { code: '#2DFFFE', lable: 'Manicure and Pedicure' },
  {code: '#FF67B3', service: 'OTHER'},
];
export const items2 = [
  {code: '#6394EB', lable: 'MAINCURE', backgroundColor: '#DFF0D8'},
  {code: '#6394EB', lable: 'PEDICURE', backgroundColor: 'white'},
  {code: '#2DFFFE', lable: 'WAX', backgroundColor: 'white'},
  {code: '#6394EB', lable: 'Refill', backgroundColor: 'white'},
  {code: '#008000', lable: 'Wax', backgroundColor: 'white'},
  {code: '#2DFFFE', lable: 'Facial', backgroundColor: 'white'},
  {code: '#0000FF', lable: 'Eyelashes', backgroundColor: 'white'},
  {code: '#008000', lable: 'Manicure and Pedicure', backgroundColor: 'white'},
  {code: '#FF0000', lable: 'order', backgroundColor: 'white'},
];
export const dataService = [
  {id: '1', name: 'Nguyen Van A'},
  {id: '2', name: 'Nguyen Van B'},
  {id: '2', name: 'Nguyen Van D'},
];
export const dataTechnician = [
  {id: '1', name: 'Nguyen Thi 1'},
  {id: '2', name: 'Nguyen Thi 2'},
  {id: '3', name: 'Nguyen Van 3'},
  // {id: '4', name: 'Nguyen Van 4'},
  // {id: '5', name: 'Nguyen Van 5'},

  // { id: '6', name: 'Nguyen Van 6' },
  // { id: '7', name: 'Nguyen Van 7' },
  // { id: '8', name: 'Nguyen Van 8' },
  // { id: '9', name: 'Nguyen Van 9' },
  // { id: '10', name: 'Nguyen Van 10' },
  // { id: '11', name: 'Nguyen Van 11' },
  // { id: '12', name: 'Nguyen Van 12' },
  // { id: '13', name: 'Nguyen Van 13' },
  // { id: '14', name: 'Nguyen Van 14' },
  // { id: '15', name: 'Nguyen Van 15' },
  // { id: '16', name: 'Nguyen Van 16' },
  // { id: '17', name: 'Nguyen Van 17' },
];
export let dataMonth = [
  {value: '1'},
  {value: '2'},
  {value: '3'},
  {value: '4'},
  {value: '5'},
  {value: '6'},
  {value: '7'},
  {value: '8'},
  {value: '9'},
  {value: '10'},
  {value: '11'},
  {value: '12'},
];
export let dataDay = [
  {value: '1'},
  {value: '2'},
  {value: '3'},
  {value: '4'},
  {value: '5'},
  {value: '6'},
  {value: '7'},
  {value: '8'},
  {value: '9'},
  {value: '10'},
  {value: '11'},
  {value: '12'},
  {value: '13'},
  {value: '14'},
  {value: '15'},
  {value: '16'},
  {value: '17'},
  {value: '18'},
  {value: '19'},
  {value: '20'},
  {value: '21'},
  {value: '22'},
  {value: '23'},
  {value: '24'},
  {value: '25'},
  {value: '25'},
  {value: '26'},
  {value: '27'},
  {value: '28'},
  {value: '29'},
  {value: '30'},
  {value: '31'},
];
//waiting_list, in_service, pending_payment

export let CUSTOMER_STATUS = {
  WAITING_LIST: 'waiting_list',
  IN_SERVICE: 'in_service',
  PENDING_PAYMENT: 'pending_payment',
};
